### ISSUE TITLE
Delaunay Triangulation: Removal of Vertices

### ISSUE THREAD

**Issue by ChristianBeilschmidt** [Stoeoef/spade#2]
Hi, do you see a possibility of adding removal operations to the Delaunay implementation? It looks like the incremental one, so I guess it should be possible.

I would be willing to help because I would like to have a Delaunay implementation for Rust that can cope with CGAL for C++.

**Comment by Stoeoef** [comment]
Hey, thanks for the feedback!
I wasn't sure how difficult removal of points in a delaunay triangulation is, after some research it doesnt seem to be too bad though. It can be done in O(n²) or O(n log n) where n is the degree of the removed vertex, I'll try to implement the most simple variant within the next week.
If you have any further Ideas on how to improve the library, please let me know - I'm eager to improve the library, I just don't know what most users really need, so a lot of low hanging fruits are yet to be picked.

**Comment by Stoeoef** [comment]
I'm halfway there - removal is supported now, but not for vertices of the convex hull.
If you want to try it out, feel free to use the master branch. I'll be releasing a new crates.io version once the removal operation is fully implemented.
CGAL also has special treatment for the removal of vertices of degree 3 to 7 which increases performance a lot. Only for vertices with higher degree, a general O(n²) flipping algorithm is implemented.
The details are described in (this paper)[http://www.sciencedirect.com/science/article/pii/S0925772110000799].
If performance is an issue for you, this will be the way to go. It's also a somewhat isolated feature, so if you want to help and dig into the project, this might be a good starting point.

**Comment by Stoeoef** [comment]
Implemented with 0bda9636e30167ce0870374e53e2d7ad84e6d7b6 .
It took a while longer since I changed a lot under the hood.
