### ISSUE TITLE
BoundingRect from points

### ISSUE THREAD

**Issue by twistezo** [Stoeoef/spade#25]
I think it will be good to have a method for creating `BoundingRect` from n-points. For now i'm doing this with `geo` crate [BoundingBox](https://docs.rs/geo/0.7.1/geo/algorithm/boundingbox/trait.BoundingBox.html) and convert its to spade `BoundingRect` for future use in `RTree`.

**Comment by Stoeoef** [comment]
Should be implemented with f8f4213 , see BoundingRect::from_points . Thanks for the suggestion!
