### ISSUE TITLE
Split off R-Tree implementation

### ISSUE THREAD

**Issue by Stoeoef** [Stoeoef/spade#27]
I'm currently working on splitting off the r-tree into its own package. One of Rusts strengths has always been Cargo, which allows to have many, small packages with a single use. R-Trees would actually be perfect in such a scenario.

I would also be looking to improve performance and to implement some more advanced algorithms - I still have some ideas for this in my mind!

I'm still looking for a good name, just in case anyone has a good idea.

**Comment by Dushistov** [comment]
Is it possible in separate create remove dependencies from huge create,
like `nalgebra`, `cgmath` and so on, or make them optional?

**Comment by Stoeoef** [comment]
`nalgebra` and `cgmath` will not be strong dependencies of the rtree split-off . I'm not sure if I am going to support them at all though, as Cargo's dependency resolution for external dependencies has it's issues at the moment (see https://github.com/rust-lang/rfcs/blob/master/text/1977-public-private-dependencies.md).

Independent on that:  I've made some good progress in the last month, I hope that I can publish my rstar repository soon! I'll keep this issue updated...

**Comment by adeschamps** [comment]
That sounds like a good design choice to me. I use `spade` with `nalgebra`, but I don't directly store `nalgebra` types in my rtree - I store a struct that contains a point and some additional data. This means that I'm implementing the `SpatialObject` trait for my type _anyway_, and `spade` having a dependency on `nalgebra` just complicates dependency resolution when `nalgebra` (or other crates that publicly depend on it) publish new versions. I would imagine that this is a fairly common situation.

Given that implementing `SpatialObject` _should_ be pretty simple, I think it makes sense for the docs to show an example of implementing it for external types, but not actually have them as dependencies.

**Comment by Stoeoef** [comment]
[rstar](https://crates.io/crates/rstar), the spade-rtree replacement crate, is out of its nursery phase!

The new r-tree implementation is not only faster, but also more feature rich and better structured - I've learned my lessons from spade.

Some features were dropped:
- No support of cgmath and nalgebra points
- No `SimpleCircle` in the predefined primitive set (although I'll probably implement that one soon)

The crate is still pre 1.0 and will undergo some breaking changes - however, I am not expecting any major breakage from one version to the next.
