### ISSUE TITLE
split SpatialObject into two traits?

### ISSUE THREAD

**Issue by Dushistov** [Stoeoef/spade#29]
I implemented `SpatialObject` (see code bellow), because of I used
only `lookup_in_rectangle`:

```Rust
#[derive(Debug, Clone)]
struct PolyObject {
    points: Vec<[f32; 2]>,
    idx: i64,
}

impl SpatialObject for PolyObject {
    type Point = [f32; 2];
    fn mbr(&self) -> BoundingRect<Self::Point> {
        let mut ret = BoundingRect::from_point(self.points[0].clone());
        for p in self.points.iter().skip(1) {
            ret.add_point(p.clone());
        }
        ret
    }
    fn distance2(&self, _point: &Self::Point) -> <Self::Point as PointN>::Scalar {
        unreachable!();
    }
}
```

May be split `SpatialObject` to two traits with `mbr` and `distance2` and require
one or another trait in special functions:

```Rust
    fn lookup_in_rectangle(&self) -> Vec<T>
    where
        T: Foo,
    {
        unimplemented!();
    }
    fn nearest_neighbors(&self) -> Vec<T>
    where
        T: Boo,
    {
        unimplemented!();
    }
```
?

**Comment by Stoeoef** [comment]
That's a good design change - thanks for the input. I'm currently rewriting the R-Tree (outsourcing it into its own repository), I'll be implementing it there. Spade will only get some maintenance updates that won't break compatibility.

Stubbing `distance2` should hopefully be a feasible workaround in the meantime.

**Comment by Stoeoef** [comment]
The spade replacement crate [rstar](https://crates.io/crates/rstar) is out of its nursing phase and will hopefully be a feasible workaround. It has the interfaces `RTreeObject` and `PointDistance` which represent the design changes discussed in this issue. `spade` itself won't have this separation.
