### ISSUE TITLE
Spade 1.5.0 is failing on nearest_neighbour queries

### ISSUE THREAD

**Issue by urschrei** [Stoeoef/spade#32]
Spade 1.4.0 works correctly, but I'm seeing test failures on nearest-neighbour queries as of Spade 1.5.0: I'm getting a `None` value when querying. The worrying thing is that I _can't_ reproduce them using Spade's native types.

This fails for our types:
https://github.com/urschrei/rust-geo/blob/5d888080885f52dc656ebf7af3ae4d423bea5aed/geo/src/algorithm/euclidean_distance.rs#L945-L966

[Source for edges which are bulk-loaded into the tree](https://github.com/georust/rust-geo/blob/master/geo/src/algorithm/test_fixtures/poly_in_ring.rs) (edges built using `windows(2)`)
[Source for points which are used to retrieve the nearest-neighbour edge from the tree](https://github.com/georust/rust-geo/blob/master/geo/src/algorithm/test_fixtures/ring.rs)

The test fails when querying using the tree using the point `(6.0001320971764285, -6.483226510722902)`

The Spade trait impls are as follows:

For `Point` (same as the `Point2` type):

https://github.com/georust/rust-geo/blob/b8354152381f735ab765847b656e12afc5117869/geo-types/src/point.rs#L297-L336

For `Line` (same as the `SimpleEdge` type):

https://github.com/georust/rust-geo/blob/b8354152381f735ab765847b656e12afc5117869/geo-types/src/line.rs#L145-L167]

Things I've checked:
- That the point values making up the `Line`s in the `RTree` are the same as those which make up the `SimpleEdge`s when running the test using Spade types ✅
- That the `mbr` values are the same for our types and for Spade Types ✅
- That the `distance2` types are the same for our types and for Spade types (in some cases, they vary in the **least significant digit**, so I don't think that's the problem)

Correct (using Spade Types):

    95.29292557779627
    100.53487738887094
    105.67537257174098
    110.66490534771486
    115.4554237886039
    120.00079258305857
    124.25723734483688
    128.1837661840736
    131.74256448158783
    134.8993590643375
    137.6237482748112
    64.54457621139609
    69.33509465228511
    74.324627428259
    79.46512261112903
    84.70707442220369
    89.99999999999997
    139.88949475560952
    141.6747781295393
    142.96240514177447
    143.73997524029863
    143.73997524029866
    45.100640935662554
    48.257435518412194
    51.81623381592642
    55.74276265516312
    59.999207416941445
    142.96240514177447
    141.6747781295393
    139.88949475560952
    137.62374827481125
    134.89935906433752
    131.74256448158786
    42.37625172518882
    40.110505244390524
    38.32522187046073
    37.03759485822556
    36.26002475970139
    36.00000000000001
    110.66490534771505
    115.45542378860407
    120.00079258305868
    124.257237344837
    128.18376618407368
    36.00000000000001
    36.26002475970138
    37.03759485822556
    38.32522187046073
    40.11050524439051
    79.46512261112939
    84.70707442220402
    90.00000000000028
    95.29292557779655
    100.53487738887117
    105.67537257174118
    42.376251725188816
    45.10064093566255
    48.257435518412194
    51.81623381592641
    55.742762655163105
    59.99920741694144
    59.999207416941815
    64.54457621139646
    69.33509465228548
    74.32462742825936

Using our types:

    95.29292557779625
    100.53487738887094
    105.67537257174098
    110.66490534771485
    115.45542378860391
    120.00079258305858
    124.2572373448369
    128.1837661840736
    131.74256448158786
    134.8993590643375
    137.6237482748112
    64.5445762113961
    69.3350946522851
    74.324627428259
    79.46512261112905
    84.70707442220369
    89.99999999999997
    139.88949475560952
    141.6747781295393
    142.96240514177447
    143.7399752402986
    143.73997524029866
    45.100640935662554
    48.25743551841219
    51.81623381592642
    55.74276265516311
    59.999207416941445
    142.96240514177447
    141.6747781295393
    139.88949475560952
    137.62374827481125
    134.89935906433752
    131.74256448158786
    42.37625172518882
    40.110505244390524
    38.32522187046073
    37.03759485822555
    36.260024759701395
    36.000000000000014
    110.66490534771503
    115.45542378860405
    120.0007925830587
    124.25723734483701
    128.18376618407368
    36.000000000000014
    36.26002475970138
    37.03759485822555
    38.32522187046073
    40.11050524439051
    79.46512261112939
    84.70707442220402
    90.00000000000027
    95.29292557779657
    100.53487738887115
    105.67537257174116
    42.37625172518881
    45.100640935662554
    48.25743551841219
    51.8162338159264
    55.742762655163105
    59.99920741694143
    59.999207416941815
    64.54457621139647
    69.33509465228549
    74.32462742825935

Has something in the `nearest_neighbour` implementation changed that could cause this?

**Comment by urschrei** [comment]
I've reduced the test case a bit. If I add edges to the tree sequentially, the query incorrectly returns `None` after I add the `Line` from point indexes 9, 10:

    vec![
        [4.0, 1.0],
        [3.9855541800165906, 0.7059485790113185],
        [3.9423558412096913, 0.41472903395161576],
        [3.8708210071966267, 0.12914596823661362],
        [3.771638597533861, -0.14805029709526818],
        [3.6457637930450657, -0.41419021047799154],
        [3.4944088369076365, -0.6667106990588052],
        [3.3190313600882124, -0.9031798524909349],
        [3.1213203435596446, -1.121320343559641],
        [2.903179852490939, -1.3190313600882089],
        [2.6667106990588096, -1.4944088369076338]
    ]

Then query for the nearest neighbour using `Point(6.0001320971764285, -6.483226510722902)`

**Comment by Stoeoef** [comment]
Thanks a lot for the report!
I'll look into that.
Nearest neighbor queries changed with 1.5 (making them faster), and my internal test (insert random points, calculate NNs from random sample points, compare with sequential calculation) usually gives me enough confidence to assume that everything is working well. Not in this case I guess...
as a workaround in the meantime (and to see if this works), feel free to try nearest_neighbor_iterator(..).next()

**Comment by Stoeoef** [comment]
I've managed to reproduce your inputs. The behaviour also only happens when using `f64.

**Comment by Stoeoef** [comment]
It seems like this is indeed a rounding issue. While searching for the NN, spade will prune branches in the r-tree if it knows that a closer point can be found.
In your example, the pruning distance is
`36.00000000000001`
The algorithm "knows" that there must be an object within this distance and will prune any object farther away. The distance to the real nearest neighbour is
`36.000000000000014`

I'll probably add a tolerance to the distance comparison, mitigating any rounding issues.

**Comment by urschrei** [comment]
Ah, fantastic. Thanks for looking into it!

**Comment by Stoeoef** [comment]
Spade v1.5.1 should fix this!
Thanks again for the detailed report, that really helped a lot.
I managed to build and test rust-geo locally with v1.5.1.

**Comment by urschrei** [comment]
Thank you!

**Comment by Dushistov** [comment]
@Stoeoef 

But where is v1.5.1? Is it secret version, because of 

https://github.com/Stoeoef/spade/blob/master/Cargo.toml

contains `version = "1.5.0"`?

**Comment by Stoeoef** [comment]
Darn, I forgot to push v1.5.1 - I have done so now. The Tag v1.5.1 refers to the correct repository state.
Thanks for the info!
