### ISSUE TITLE
Release new Spade version

### ISSUE THREAD

**Issue by nevi-me** [Stoeoef/spade#40]
Hi, looks liike upgrading `num = 0.2` was significant as it gets rid of `rustc-serialize` which is deprecated. I'm using `rust-geo`, and was trying to compile it to wasm. I forked the repo and updated spade to the commit which updates num, and that allowed compiling to wasm.

May you please kindly release an update to spade (I assume it could be 1.5.2?). rust-geo already uses serde and the `num-* = 0.2` family, so the update wouldn't be a breaking change to the library.

Thanks

This is related to https://github.com/georust/geo/issues/245

**Comment by Stoeoef** [comment]
Hi, I published v1.6.0, which uses 0.2.* as num reference.
