### ISSUE TITLE
Spade 2.0

### ISSUE THREAD

**Issue by Stoeoef** [Stoeoef/spade#45]
Even though the project is set to passively maintained, I'm currently working on a large refactoring in the background. Here's an issue to discuss what Spade's current shortcomings are and how I plan to overcome them. Please, do feel free to start a discussion!
That said, if you are interested in using spade, please don't be dismissed by this issue as it deliberately focuses only on the _negative_ parts of Spade: It is still a feature rich and easy to use computational geometry library (let  me know if you disagree!) that has proven itself in my personal projects. My experiences culminated in the ideas discussed here.

#### Too many features
These features should probably be split into their own crates if required or be removed entirely
  - Integer coordinates (along with the adaptive int kernel)
  - `f32` support (it is still possible to use `f32` for storage, but it will be casted to `f64` for calculation purposes)
  - locate strategies. Those can probably be implemented on top of the triangulation.
  - integration into `cgmath` and `nalgebra`, if the integration is kept, only feature gated and as a re-export
  - farin interpolation
  - Calculation Kernels should probably become an implementation detail, I don't see much sense for supporting the `TrivialKernel` at the moment.
 - rtrees (These have already been extracted into the `rstar` crate)

#### Some missing features
- Bulk loading for triangulations
- Custom edge and face types
- Performance. Spade was not really focused on performance so far, I want to make this more of a priority.

### Design changes
I believe that spade should be designed to be a "backend" for Delaunay related algorithms.
Interpolation is a good example: Even today, interpolation algorithms can be implemented efficiently by using the current public API. Interpolation should probably be moved to a separate module or even its own crate.
It may (I'm investigating that one) even be possible to implement the CDT based on the public Delaunay API.
Finding the right design would allow to create custom tailored algorithms fitting many niches (e.g., alpha shapes).

Also, I plan to change an algorithmic technicality (although an influential one): The introduction of the "infinite point". This is an imaginary point "infinitely far away" from any other point, it is connected to _every_ point of the convex hull. The main motivation is simplicity, I hope that the introduction will simplify the handling of the convex hull _significantly_ and improving performance. However, I'm still unsure how and if this point should be part of the public API.

### Open questions
- I'm not 100% sure if a 2.0 release or a split off as a new package is more apt, but I'm in favour of creating a new package (similar to the `rstar` outsourcing)
- Should the infinite point become an implementation detail or be part of the public API? 
- If it becomes part of the public API, how should it be handled? Is it a regular vertex whose position is never evaluated? Can `VertexHandle` point to the infinite point?

### Current Status
This reflects the status of my local prototype, I plan to upload it onto a branch once the dust settles a bit. The steps are roughly ordered according to when I want to work on them:
- [x] Removal of most of the above "unwanted features"
- [x] Locate in triangulation queries
- [x] Insertion
- [x] Infinite point
- [x] Vertex removal
- [x] CDT
- [x] Performance benchmarks
- [x] Documentation updates
- [x] Bulk loading

### Final notes
Please, do feel free to open a discussion - there are many moving parts that need to be settled. If you even want to dive deeper, I'll happily answer questions or will mentor any kind of contribution.

**Comment by rmanoka** [comment]
Happy to contribute to this effort.  Concretely,  I could help with benchmarks.  We have some code that interpolates points to a raster (by interpolating pixel wise).   We could run this on a open GIS datset available and it should provide us benchmarks for:
  1. Delauney triangulation of n points
  1. Random update (add one point) on existing triangulation
  1. Interpolation times per point

Would also be interested in looking at bulk loading.  Could you explain in more details on how you want to support it / how it is not available now?

I'm generally also looking at providing (or using if already available) support to incrementally build the triangulation, and get a "delta" of what faces changes.  This is useful to do incremental interpolation, where the source point cloud changes minimally.   Please share your thoughts on this too.

**Comment by Stoeoef** [comment]
> We could run this on a open GIS datset available and it should provide us benchmarks for:

That would be greatly appreciated! The benchmarks I had in place so far tend to be not complete (they don't cover interpolation methods or removal as far as I know), nor do they work with real GIS data.

In regards to the "random update" benchmark: The performance is mainly dependent on the "hint vertex" where the triangulation starts looking for the position of the inserted vertex. Maybe this benchmark should be split into two parts, one for locating the right insertion hint, one for the actual insertion. Anyway, that's already pretty detailed, it's just a heads-up about what might be involved. The results of the benchmarks I ran back then can be found [here](https://stoeoef.gitbooks.io/spade-user-manual/content/triangulation-performance.html).

> Would also be interested in looking at bulk loading. Could you explain in more details on how you want to support it / how it is not available now?

Spade currently _doesn't have_ bulk loading for triangulations. A triangulation is created by sequentially adding all points. This yields a total creation time of usually `O(n log (n))` or `O(n sqrt(n))`.
Bulk loading strategies tend to achieve `O(n log(n))` average runtime, which is also the theoretical best possible time. However, they should have much lower constant factors.

Wikipedia leads to [this paper](https://people.eecs.berkeley.edu/~jrs/meshpapers/SuDrysdale.pdf), which seems to be a good starting point for an investigation.
The [delaunator](https://github.com/mourner/delaunator-rs) crate is also noteworthy and supposedly way faster than spade, they seem to sort the input points on one axis and then build the triangulation from "left to right". The above paper outlines some seemingly similar algorithms.
As always, I'm wondering "what would CGAL do?", that should also be worth a look.
As said, I have not yet investigated the current state of the art for bulk loading nor am I an expert on that matter, please share what you know!

> I'm generally also looking at providing (or using if already available) support to incrementally build the triangulation, and get a "delta" of what faces changes. This is useful to do incremental interpolation, where the source point cloud changes minimally. Please share your thoughts on this too.

The information which new faces are created and which are being modified could be easily provided, it is just not being tracked at the moment. I'm unsure on how to bundle this up in a nice API, as that's probably not a too common feature.
However, the information which vertices, faces and edges changed can be genuinely useful (I have had some use cases in mind myself), I'm open for exploration in this field. Internally, for example, the triangulation must also update the vertex id in the accompanying rtree whenever a vertex is removed, which already uses a returned value indicating which ids need to be updated. Similar strategies could be provided to return information about which faces and edges changed. I have no specific idea for this but will keep it in mind when doing the API design.

**Comment by hugoledoux** [comment]
First, many thanks for spade, I learned and still learning from looking at the code. I am using your port of Shewchuk's robust predicates for my project (https://github.com/hugoledoux/startin), and it's great. I started with using the C code directly, but I have python bindings and playing with wasm so pure rust is great.

  > The delaunator crate is also noteworthy and supposedly way faster than spade

I benchmarked quickly some of the triangulators and  delaunator is *not* way faster than spade at all. It is for one specific case: points that are randomly generated in a square (and thus have no spatial coherence). If the `walk_locate()` is used for spade, then for 1M randomly generated points spade is 125X slower, but if I switch to the rtree walk than it's ~6X slower. For the dataset I'm dealing with (airborne LiDAR datasets), the spatial coherence is usually good and spade and delaunator are more or less the same. And spade has robust arithmetic, which slows down.

What I would advise is perhaps analyse quickly a dataset (if it's known in advance) and then decide which walk strategy is best; I'll implement this in my project eventually.

I would favour keeping an incremental algorithm for 2.0, since it allows a lot of operations on the triangulation (interpolation with Sibson's method for instance) and many applications require insertion/deletion (for processing of LiDAR it's essential); speed is only one factor.

> Should the infinite point become an implementation detail or be part of the public API?

My triangulator uses the infinity point (https://github.com/hugoledoux/startin), and indeed I struggle to decide whether it should be exposed at all to the API and users. CGAL does expose it. Perhaps the rationale is that if you dig into the data structure it's useful to see it and to be aware; but if you use the code has a black box to triangulate then you won't care and won't notice it anyway.

**Comment by Stoeoef** [comment]
Thank you for your kind words @hugoledoux !

> I benchmarked quickly some of the triangulators and delaunator is not way faster than spade at all.

Thanks for doing the comparison with Delaunator - my knowledge was base on [this reddit thread](https://www.reddit.com/r/rust/comments/9gj0uk/introducing_delaunator_a_blazing_fast_static_2d/). Good news for spade, it's clunky algorithm always *seemed* to be slow for me, but I never really put it into comparison.

> I would favour keeping an incremental algorithm for 2.0

No worries, incremental insertion is still planned. How is Sibson interpolation related?

> My triangulator uses the infinity point (https://github.com/hugoledoux/startin), and indeed I struggle to decide whether it should be exposed at all to the API and users. 

Good to know that you struggle with the same problem... that one single point makes way more problems than I originally anticipated.
I'm not hesitant to  expose the infinite vertex in general. I just don't know how to present a triangulation with no or exactly one non-infinite vertices *nicely*.
After doing some exploration in this area, I decided to keep Spade's approach for the public interface and the internal storage. Spade distinguishes between "degenerate" triangulations where all vertices lie on a single line (this includes triangulations with zero, one or two vertices). This model is really simple to visualize and use, hence I would like to keep it.
However, the internal legalize edge algorithms become *really* elegant when using an infinite vertex. I'm currently trying to get the best out of both by generating infinite edges "on the fly" during edge legalization which will hopefully lead to a nicer algorithm design than what Spade currently has.

> For the dataset I'm dealing with (airborne LiDAR datasets), the spatial coherence is usually good

That sounds like a really cool use case! Thanks for sharing your project.

**Comment by hugoledoux** [comment]
I had read the same reddit thread and thought "no way", so I benchmarked them. If you want an example of a LiDAR dataset I transformed to a simple format a 27M dataset somewhere in the Netherlands, it's there:
https://www.dropbox.com/s/juqgjiepv2pxapy/c_37en1_big_delft.txt?dl=0
It's open data, and from that dataset: 
https://www.pdok.nl/nl/ahn3-downloads

I now expose in the data structure the infinity point, but if one wants a list of triangles then she gets only the finite ones. For me the infinity helped in making the algo more elegant as you say, but there are still in practice many things to take care (never doing an incircle() test with that point for example; insertion outside the convexhull and thus inside and infinite triangle, etc.). But worth it.

Sibson interpolation is easiest to implement by insertion, calculation of stolen areas, and deletion. If you already have an incrementation insertion you have all the machinery necessary. Delaunator will have to implement the walk(), the insertion, etc.

**Comment by Stoeoef** [comment]
Sorry all for the long delay. However, I'm happy to announce that I've finally managed to release spade 2.0 and have continued to develop Spade.

Some notes:
 - Performance should have improved with the new bulk load method. The above triangulation (big_delft.txt) takes between 17 - 20s to triangulate on my machine (excluding parsing time).
 - After experimenting with it, I've decided against the infinite point. While it did simplify _some_ parts of the algorithm, it made using the triangulation more tricky. I was especially uncertain about how to handle "empty" triangulations - the best solution I could come up with was to have 3 infinite vertices in this case, complicating matters a lot
 - I've taken out interpolation (for now) to get this in a releasable state - see #67

**Comment by Stoeoef** [comment]
For reference: This is what the above file looks like when rasterized:

![example](https://user-images.githubusercontent.com/5731969/151660001-7b588935-0ef8-4608-bb1d-98a3dfa790e1.png)

Reading in the coordinates _and_ their heights seems to increase the loading time to something slightly above 20s.
