### ISSUE TITLE
incircle predicate produces results that differ from original C code

### ISSUE THREAD

**Issue by bmmeijers** [Stoeoef/spade#48]
While verifying the exact predicates implementation in Rust, I found that your
incircle code produces results that differ from the original predicates code in
C.

The problem lies in the following lines in exactpred.rs (lines 337-343):

```
        let mut aytcc = [0f64; 8];
        let aytcclen = scale_expansion_zeroelim(&cc, adytail, &mut aytcc);
        let temp16blen = scale_expansion_zeroelim(&aytcc[..aytcclen], cdx, &mut temp16b);

        let mut aytbb = [0f64; 8];
        let aytbblen = scale_expansion_zeroelim(&bb, adytail, &mut aytbb);
        let temp16clen = scale_expansion_zeroelim(&aytbb[..aytbblen], -bdx, &mut temp16c);
```

These lines should be changed as follows (variables named '*cc*' have been swapped with '*bb*' and vice versa):

```
        let mut aytbb = [0f64; 8];
        let aytbblen = scale_expansion_zeroelim(&bb, adytail, &mut aytbb);
        let temp16blen = scale_expansion_zeroelim(&aytbb[..aytbblen], cdx, &mut temp16b);

        let mut aytcc = [0f64; 8];
        let aytcclen = scale_expansion_zeroelim(&cc, adytail, &mut aytcc);
        let temp16clen = scale_expansion_zeroelim(&aytcc[..aytcclen], -bdx, &mut temp16c);
```

Note, the following are the original lines in predicates.c (lines 2839-2843):

```
    aytbblen = scale_expansion_zeroelim(4, bb, adytail, aytbb);
    temp16blen = scale_expansion_zeroelim(aytbblen, aytbb, cdx, temp16b);

    aytcclen = scale_expansion_zeroelim(4, cc, adytail, aytcc);
    temp16clen = scale_expansion_zeroelim(aytcclen, aytcc, -bdx, temp16c);
```

After this change, the Rust incircle code produces identical results to the 
original C code.

**Comment by Stoeoef** [comment]
Woah, thanks for finding this. I wonder how many other errors may have been introduced during the manual translation. Maybe it's time to do this properly with a C to rust converter. I know they're error prone, but since the underlying C files are really simple, the may actually work in this case.

Related to [this issue on geo](2839).

**Comment by bmmeijers** [comment]
As far as I can tell, the orient2d and incircle code are now correct.

I've been running quite some random calculations (either point close to nearly straight line for orient2d, or close to unit circle for incircle) and I've not observed any differences between the results from predicates.c and the Rust code.

**Comment by Stoeoef** [comment]
> As far as I can tell, the orient2d and incircle code are now correct.
> 
> I've been running quite some random calculations (either point close to nearly straight line for orient2d, or close to unit circle for incircle) and I've not observed any differences between the results from predicates.c and the Rust code.

That sounds promising, thanks for doing this and sharing the results.
I'll close the issue once I've published a new version.

**Comment by Stoeoef** [comment]
The predicates have been moved to crate `robust`. Closing.
