### ISSUE TITLE
Add Voronoi Computation

### ISSUE THREAD

**Issue by cannontwo** [Stoeoef/spade#51]
I'm currently building on Spade to compute Voronoi diagrams for some research code, and I'm wondering if you'd be interested in getting a pull request to add this as a module. I understand that (c.f. #45) you want to avoid feature bloat, but this seems like it should be a fairly common use case of a Delaunay triangulation library (and small enough of an addition not to merit another crate).

**Comment by Stoeoef** [comment]
Thanks for offering a PR for Voronoi computation! And sorry for the late reply :( .

Actually, Voronoi Diagrams are probably more common than using a Delaunay Triangulation directly. This definitely makes this a missing high priority feature of Spade. The major reason why they are not part of Spade is that I have not needed them for myself so far and nobody has actively asked for them.

As you have mentioned there are some moving parts in the background - Spade 2.0 is far enough progressed that I can (and should!) upload my local progress, adding Voronoi computation to 1.x will require that it is ported over to 2.0. I'd suggest one of three options, let me know what you think:

 - Base the PR on Spade 1.x - I will gladly review a PR and would expect that much of the code can be ported over. If you intend to use a crates.io version of Spade for your projects, this is the easiest option. Also, much of the design work (how does an interface for accessing the Delaunay diagram look like?) does not really depend on which version it lands in, I'd be interested to see how this shakes out rather early than later.
- Base the PR on the Spade 2.0 alpha. This will not allow a crates.io build in the near future if that's what your looking for but will not require any porting. I can provide the alpha version but would expect a bumpy road ahead as there are still moving parts and not much documentation. 
- Hold this PR and wait until 2.0 is more stable (or even released) and then base a PR on that. This would simplify things when implementing the PR. It'll take me a while to get there, though...

Let me know what you think and thanks again for offering this PR! Any of these options will improve Spade and I'm happy with all of them.

**Comment by cannontwo** [comment]
I'm glad to hear that you're interested! I'll probably move forward with the first option, since I've put together some code already using the crates.io version of Spade. I also don't mind doing the porting once 2.0 comes out, since I'll want to keep using the Voronoi code anyway.

I'll be a slow mover on this PR myself, as it's sort of tangential to my main PhD work, but I intend to have a PR in sort of good shape in about a month.

**Comment by Stoeoef** [comment]
Wonderful!

I'll make sure to review any PR. If you stumble upon any questions or problems, feel free to ask or upload a WIP

**Comment by jomala** [comment]
`rstar` looks to have reached a good stage. Any plan to return your focus to spade 2.0, @Stoeoef?

Thanks you for your work so far!

**Comment by Stoeoef** [comment]
Sorry for my long out time. But: Yes, I've returned my focus on spade (wohoo). Basic Voronoi computation (that means: ignore any overlapping Voronoi vertices and Voronoi faces with an area of zero) has been part of the Spade 2.0 release. I think that should be sufficient to get most people started - closing!
