### ISSUE TITLE
Support for constrained Delaunay triangulation with holes

### ISSUE THREAD

**Issue by agersant** [Stoeoef/spade#58]
Hello and thank you for all the hard work on Spade. It is a very useful library and I've had great success using it.

## Context

I am using Spade to generate [navigation meshes](https://en.wikipedia.org/wiki/Navigation_mesh) in a 2D video game. The inputs I give to Spade are the four corners of the playable space, and constraint edges representing all the polygonal obstacles within it. The resulting triangulation is a usable navigation mesh, PLUS unwanted faces within the obstacles.

My current approach to get rid of these unwanted faces is to inspect every face in the triangulation, and store which ones happen to be within obstacles. Whenever I make use the triangulation to compute paths, I simply ignore all these unwanted faces.

This image shows a playable space with red polygonal obstacles and the corresponding triangulation in cyan. Notice the many triangles overlapping the red obstacles:
![small-navigation-mesh-actual](https://user-images.githubusercontent.com/817256/90328139-f93a1d80-df4e-11ea-9ebd-fb037a06c0fe.png)

This image shows the same triangulation, excluding the unwanted faces:
![small-navigation-mesh-actual](https://user-images.githubusercontent.com/817256/90328133-e6bfe400-df4e-11ea-9a20-ea2cd9f58879.png)

*Sidenote: you may have noticed that the vertices in the triangulation are slightly offset from the obstacle vertices - that is intentional and not important for this discussion*

## Problem

The limitation of this approach is that calls to `locate()`, which are very useful to rein in stray game characters, have no way to ignore the extra faces.

I did manage to work around this by first projecting my arbitrary point onto the playable space without using Spade, and then calling `locate()` using that point. However, this is a fairly finicky and error-prone process.

## Suggestion

In the past, I used [Triangle](https://www.cs.cmu.edu/~quake/triangle.html) to generate these navigation meshes. A very convenient feature of Triangle is that it supports the concept of 'holes', which can be used to eliminate unwanted faces from the output. The first example on [this page](https://www.cs.cmu.edu/~quake/triangle.demo.html) illustrates the idea, with the inside of the `CMU` letters not being filled with faces: 
![image](https://user-images.githubusercontent.com/817256/90328222-a319aa00-df4f-11ea-91af-d77d8c4c2424.png)

An important subtlety is that holes can have holes themselves. In Triangle, this is implemented by specifying the triangulation input in three parts:
- Vertices (same as Spade)
- Segments (same as constraint edges in Spade)
- Holes (one point per hole)

Here is how they describe the implementation of the holes:

> The third section lists holes (and concavities, if -c is selected) in the triangulation. Holes are specified by identifying a point inside each hole. After the triangulation is formed, Triangle creates holes by eating triangles, spreading out from each hole point until its progress is blocked by PSLG segments; you must be careful to enclose each hole in segments, or your whole triangulation might be eaten away. If the two triangles abutting a segment are eaten, the segment itself is also eaten. Do not place a hole directly on a segment; if you do, Triangle will choose one side of the segment arbitrarily.

Many thanks in advance!

**Comment by Stoeoef** [comment]
Thanks for the report!

If I understand you correctly you are looking for a way to find out if a face is an inner face. Additionally, you may want to find the closest point in the playable area.

Unfortunately, I don't think that the holes solution would fix that issue: Calling `locate` requires that the inner edges of a hole exist. `locate` works by "walking" through the triangulation (starting at a random point), getting closer to the target point with each step. If the walk encounters a hole, it needs these inner edges to "cross" the hole and get to the other side.

I believe that annotating the (directed) constraint edges of a hole would work for your use case. At least that's what I've done a while ago when I was facing the same problem. You could `locate` a face, inspect its directed edges and then conclude that it must be an inner face. Once you have identified the inner face, getting the closest non-hole edge or vertex should (hopefully?) be doable, although my memory is a bit vague on that one.

Here's an image that illustrates better what I mean:
![InnerFaces](https://user-images.githubusercontent.com/5731969/90330888-8792bb80-dfb0-11ea-96f9-4eca9c2c0555.png)

The blue edges are annotated as "inner" edges. Red edges are annotated as "outer".
To identify if a face is an inner face, you would take any of its edges and rotate that edge clock wise (by calling `edge.cw()`) until two constraint edges (edges of the hole) are found. Now there are two possible scenarios:
 - The first edge is marked as "inner", the second edge is marked as "outer". Then the face will be an inner face.
 - The first edge is marked as "outer", the second edge is marked as "inner". Then the face will be an outer face.

-----------------------------------------------
Annotating an edge as "inner" or "outer" could be done with  a `HashSet` at the moment.
That being said, I agree that Spade could have a nice API to support this scenario, e.g. specialised `HoleCDT`.

**Comment by agersant** [comment]
Thank you very much for the detailed answer.

## Identifying inner faces
I like your suggestion for telling inner faces apart from outer ones by inspecting edges. It sounds a lot more elegant than my current geometric brute-force, which detects intersections between face triangles and playable space using the `geo` crate. 

However, I am not confident your suggested approach would work for all cases. In the image below, I marked one of the faces with an `X`. This face is within an obstacle, but none of its edges are constraint edges. The other large triangle immediately to its bottom right is in the same situation. 

![image](https://user-images.githubusercontent.com/817256/90332460-e38a1f80-df71-11ea-80e1-e5bb494804ba.png)

Note that there are also faces fully contained in the playable space with none of their edges being a constraint edge (eg. the largest triangle in the top-center of the image).

## Locating nearest point in playable space

I'm sad that decimating a bunch of faces from the triangulation would not make `locate()` magically work for my use case. It was a good dream while it lasted 😂. Thanks for explaining how it works.

You do bring up a good point about finding the nearest playable vertex/edge from whatever `locate()` gives me. Even if locate returns a face within an obstacle, it's very easy to find reasonable candidates nearby by looking at faces who share vertices with the invalid one. I'll try something along these lines.

**Comment by Stoeoef** [comment]
> However, I am not confident your suggested approach would work for all cases. In the image below, I marked one of the faces with an X. This face is within an obstacle, but none of its edges are constraint edges. The other large triangle immediately to its bottom right is in the same situation.

I'm aware of that. That's why deciding if a face is an inner face or not is definitely more complex than just checking if any of its edges is marked as an inner edge.
The above solution should work for the face you've marked as well. Take any of the face's edges and start *rotating* them around their source vertex. Once the rotation encounters a boundary edge, it can stop and draw conclusions like this:
 - If the `outgoing_edge` is marked as "normal" and `outgoing_edge.sym()` is marked as "inner", all previous edges were also part of an inner face.
 - If the `outgoing_edge` is marked as "inner" and `outgoing_edge.sym()` is marked as "normal", all previous edges are also part of an outer face.

This should look a bit like this pseudo-rust:

```rust
let mut rotating_edge = face.out_edge();
loop {
  rotating_edge = rotating_edge.cw();
  let is_outgoing_edge_marked = is_inner_edge(rotating_edge); // Looks up the edge label, e.g. with a HashSet.
  let is_incoming_edge_marked = is_inner_edge(rotating_edge); // Returns a bool
  if is_outgoing_edge_marked != is_incoming_edge_marked
  {
    if is_outgoing_edge_marked
    {
      /// return that face is an inner face
    } else {
     // return that face is an outer face
    }
  }
}
```

Sorry for the confusing description, it's a bit hard to describe this algorithm just with words!

**Comment by agersant** [comment]
Oh I see. I had misunderstood what `edge.cw()` would do, I didn't realize it would iterate on the edges around the source vertex - I thought it was just going around the face. I think this is enough to get me going, thanks again for your help!

I'll post an update when I'm done updating my code but feel free to close this is you want.

**Comment by agersant** [comment]
Your algorithm to detect inner faces works flawlessly. In case anyone else ends up here from a search, here is the code I ended up with:

```rust
fn compute_navigable_faces(
  &self,
  triangulation: &Triangulation,
  obstacle_edges: &HashSet<usize>,
) -> HashSet<usize> {
  let mut navigable_faces = HashSet::new();
  'face_loop: for face in triangulation.triangles() {
    if let Some(edge) = face.adjacent_edge() {
      for edge in edge.ccw_iter().skip(1) {
        let outgoing_obstacle = obstacle_edges.contains(&edge.fix());
        let incoming_obstacle = obstacle_edges.contains(&edge.sym().fix());
        if outgoing_obstacle != incoming_obstacle {
          if incoming_obstacle {
            navigable_faces.insert(face.fix());
          }
          continue 'face_loop;
        }
      }
    }
  }
  navigable_faces
}
```

**Comment by Stoeoef** [comment]
I'm currently cleaning up old issues - this seems to be resolved. Let me know otherwise!

Adding an "official" flood fill algorithm to mark inner / outer faces might be a nice addition at some point.
