### ISSUE TITLE
Feature request: face handle of point contained in delaunay triangulation face

### ISSUE THREAD

**Issue by legendofa** [Stoeoef/spade#59]
I am currently missing the functionality to get a `FixedFaceHandle` or `FaceHandle<V>` from a specific point.

<img src="https://user-images.githubusercontent.com/34162874/95453942-42a95680-095b-11eb-8baf-6ecdbc82dc2e.png" width="300">

Maybe i am overlooking something, otherwise this would be a useful additional feature.

```rust
///
/// Containing face of certain point. Returns None if face is incomplete.
///
fn containing_face(&self, point: &V::Point) -> Option<FaceHandle<V>>
```

**Comment by Stoeoef** [comment]
Sorry for the long delay. This is actually already part of the library with the locate function (https://docs.rs/spade/2.0.0/spade/trait.Triangulation.html#method.locate)

Code sample:
```rust
match triangulation.locate(Point2::new(x, y)) {
        spade::PositionInTriangulation::OnVertex(_) => todo!(),
        spade::PositionInTriangulation::OnEdge(_) => todo!(),
        spade::PositionInTriangulation::OnFace(face) => {
            // Do something with face
        },
        spade::PositionInTriangulation::OutsideOfConvexHull(_) => todo!(),
        spade::PositionInTriangulation::NoTriangulation => todo!(),
    }
```
