### ISSUE TITLE
Various iterators (e.g FacesIterator) absent from documentation

### ISSUE THREAD

**Issue by Restioson** [Stoeoef/spade#60]
When looking at some iterator-returning functions, there is no corresponding documentation for the iterators. For instance, take FacesIterator:

![screenshot showing no results found for FacesIterator](https://user-images.githubusercontent.com/6688948/97110185-7963c880-16e0-11eb-8e60-2ee2264713fb.png)

([Link](https://docs.rs/spade/1.8.2/spade/delaunay/struct.DelaunayTriangulation.html?search=FacesIterator))

This makes it difficult to know which exact type it iterates over, etc.

**Comment by Stoeoef** [comment]
Thanks for the report (and sorry for the late reply)!

I've added a `![warning(missing_docs)]` these days, that should take care of that.
