### ISSUE TITLE
Wrong links

### ISSUE THREAD

**Issue by tatref** [Stoeoef/spade#61]
Hi,

In the user manual, chapter Introduction, section Further Resources, the link for the doc points to "https://stoeoef.gitbooks.io/spade-user-manual/content/docs.rs/spade/"
I think this should be https://docs.rs/spade/

On the crates.io page, the link "Using Spade" points to https://crates.io/crates/spade#using-spade, that section doesn't appear to exits.

**Comment by Stoeoef** [comment]
Thanks for the report (and sorry for the late reply)! I'm planning to discontinue the user manual and try to document everything in the official rust documentation. Hence, closing as a won't fix.
