### ISSUE TITLE
Kernel definition

### ISSUE THREAD

**Issue by jomala** [Stoeoef/spade#62]
I've been trying to test the extensibility of spade by implementing a kernel for points on the unit sphere. The major issue I've hit is that `pub trait DelaunayKernel<D: SpadeNum>` is defined in terms of `D` rather than `V: TwoDimensional<Scalar = D>`, which (I think) means that the functions have to be implemented for all types `V` and can only use functions defined for trait `TwoDimensional`. Could it not be defined as pub trait DelaunayKernel<V: TwoDimensional<Scalar = D>>` instead?

Also, would a better default `fn contained_in_circumference()` not just be based on `side_query()`? Or is that inefficient?

(I think this relates to https://github.com/Stoeoef/spade/issues/28 but I'm not having the same issue that reporter was.)

**Comment by Stoeoef** [comment]
I've removed `DelaunayKernel` in Spade 2.0 for now. IMO, there were no real use cases for any other kernel than the precise calculation kernel. Thus, this issue shouldn't apply anymore.

In regards to `contained_in_circumference` I'm a little confused - checking for circumference (of a triangle) is a different, more labour intensive operation than checking for orientation (side query). Maybe I misunderstand (please correct me if I do), but I don't believe `contained_in_circumference` can, in general, reduced to a simpler operation.
