### ISSUE TITLE
intersects_constraint return type

### ISSUE THREAD

**Issue by nowakf** [Stoeoef/spade#70]
A lot of the time, when you call intersects_constraint, you're interested in which constraint you're intersecting, e.g.  so you can get rid of it, or alter it, etc.

Do you think it would make sense for intersects_constraint to return Option\<DirectedEdgeHandle\> or something?

Can write a patch if you are interested.

**Comment by Stoeoef** [comment]
Implemented in v2.8.0 via `LineIntersectionIterator` and `Cdt::get_conflicting_edges_between_point` / `...between_vertices`.

Closing
