### ISSUE TITLE
how to get a vertex by index?

### ISSUE THREAD

**Issue by ogau** [Stoeoef/spade#83]
Example is just for clarity of what I need. Something like:
```
let tri = spade::DelaunayTriangulation::bulk_load(points).unwrap();
let index = 111;
let vert = tri.vertices().nth(index).unwrap();
```
I understand that points are sorted inside the builder, but my code takes this order into account

**Comment by Stoeoef** [comment]
There's a decent chance that `nth()` will actually be optimized to what you want and become an O(1) operation.

But this hints at a good improvement: We should manually overwrite `nth`, `nth_back` , `advance_by` and `advance_back_by` as they're all specialised for the underlying range.
